##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: 


obj-$(CONFIG_PROXIMITY_CM3607)	+= cm3607.o
obj-$(CONFIG_PROXIMITY_GP2A)	+= gp2a_prox.o



